project:
  type: website
  output-dir: docs

website:
  title: "Poverty Data Gaps"
  site-url: "https://royal-statistical-society.github.io/poverty-data-gaps"
  image: "assets/img/featured.png"
  favicon: "assets/img/favicon.ico"
  twitter-card: true
  open-graph: true
  page-footer:
    border: true
    background: "#004b6c"
    foreground: "white"
    center:
      - text: "Â© Copyright 2026 The Royal Statistical Society. Registered charity in England and Wales. No.306096."
  navbar:
    search: true
    logo: "assets/img/logo-white.svg"
    logo-alt: "RSS logo"
    pinned: true
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme: [flatly, assets/css/custom.scss]
    toc: true
    toc-location: left
    page-layout: full
    code-overflow: wrap

execute:
  echo: false
  eval: true
  warning: false
  message: false
